blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/PebbleTemplates/pebble/security
    about: Privately disclose a vulnerability
  - name: Community Support
    url: https://github.com/PebbleTemplates/pebble/discussions
    about: Please ask and answer questions here.